#!/usr/bin/env bash
IMAGE="ipunktbs/php-composer:7.0.9-1.2.0"
USERID=$(id -u)
GROUPID=$(id -g)
DIRECTORY="/user/src/admin-local-php7"
CACHE_VOLUME="composer-cache"

if tty 2>&1 > /dev/null ; then
        INTERACTIVE="-it"
else
        INTERACTIVE=""
        echo "No terminal detected, running in non-interactive mode"
fi

if ! (docker volume ls | grep $CACHE_VOLUME) ; then
	docker run -v "$CACHE_VOLUME:/.composer" alpine:3.4 chmod 777 /.composer
fi

case $1 in
	self-update)
	UPGRADE_SCRIPT="/tmp/upgrade-composer.sh.$$"
	wget https://raw.githubusercontent.com/ipunkt/composer.sh/master/upgrade-composer.sh -O "$UPGRADE_SCRIPT"
	exec bash "$UPGRADE_SCRIPT" $0
	;;
	*)
		docker run $INTERACTIVE --rm --hostname php7 -e "LOCAL_USER_ID=$USERID" \
			-e "COMPOSER_CACHE_DIR=/.composer" \
			-v "$CACHE_VOLUME:/.composer" \
			-v $(pwd):"$DIRECTORY" \
			-w "$DIRECTORY" \
			"$IMAGE" composer $*
		;;
esac
